[package]
name = "emu98"
version = "0.3.1"
edition = "2024"

[dependencies]
anyhow = "1"
env_logger = "0.11"
log = "0.4"
ureq = { version = "3.2.0", features = ["rustls"] }
zip = "8.1.0"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
lto = true
