name: Build and Release

on:
  push:
    tags:
      - 'v*' # Push events to tags like v1.0, v20.15.1

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Add Windows and Linux targets
      run: |
        rustup target add x86_64-pc-windows-gnu
        rustup target add x86_64-unknown-linux-gnu

    - name: Install cross-compiler for Linux
      run: brew install x86_64-unknown-linux-gnu

    - name: Build for macOS
      run: cargo build --release --target x86_64-apple-darwin

    - name: Build for Windows
      run: cargo build --release --target x86_64-pc-windows-gnu

    - name: Build for Linux
      run: cargo build --release --target x86_64-unknown-linux-gnu

    - name: Package macOS binary
      run: |
        mkdir -p artifacts/macOS
        cp target/release/emu98 artifacts/macOS/

    - name: Package Windows binary
      run: |
        mkdir -p artifacts/Windows
        cp target/x86_64-pc-windows-gnu/release/emu98.exe artifacts/Windows/

    - name: Package Linux binary
      run: |
        mkdir -p artifacts/Linux
        cp target/x86_64-unknown-linux-gnu/release/emu98 artifacts/Linux/

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: artifacts/
